// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import ()

type User struct {
	ID        int64
	Name      string
	CreatedAt string
	UpdatedAt string
	ApiKey    string
}
